### ISSUE TITLE
Cannot figure out how to set the Javascript (Analytics.JS) source's settings

### ISSUE THREAD

**Issue by dossy** [segmentio/terraform-provider-segment#106]
The [documentation](https://github.com/segmentio/terraform-provider-segment/blob/f6ce65e4a3924da3e5401e1a50a0ec75c484de49/docs/resources/source.md?plain=1#L71) for `segment_source` suggests that it may be possible to set a source's settings with it.

It doesn't appear to work.

Try this:

```terraform
terraform {
  required_version = ">= 1.0"

  required_providers {
    segment = {
      source  = "segmentio/segment"
      version = "1.0.0"
    }
  }
}

resource "segment_source" "test" {
  slug    = "test_source"
  name    = "Test Source"
  enabled = true

  metadata = {
    id = "IqDTy1TpoU" # Javascript (Analytics.JS)
  }

  settings = jsonencode({
    website_url = "https://www.segment.com"
  })
}
```

Applying that creates a source whose Settings looks like this:

<img width="936" alt="image" src="https://github.com/segmentio/terraform-provider-segment/assets/65378/ffedde0b-e97e-44d0-85fd-0c1d0b967807">

No value in the "Website URL" setting.

Am I using the wrong key in the setting value in the resource?  Is there a place in the documentation where the correct key strings can be found for each source?

**Comment by deanhuynh** [comment]
Thanks for your question! Can you try the format from the documentation [here](https://registry.terraform.io/providers/segmentio/segment/latest/docs/resources/source)? The settings should be in JSON.

**Comment by dossy** [comment]
@deanhuynh The documentation has this:

```terraform
  settings = jsonencode({
    "token" : "xyz321",
  })
```

while my test case has:

```terraform
  settings = jsonencode({
    website_url = "https://www.segment.com"
  })
```

Use of colons in Terraform map object literals [was supported](https://developer.hashicorp.com/terraform/language/v1.1.x/configuration-0-11/syntax) in Terraform v0.11, but from Terraform v0.12 onward has been [changed](https://developer.hashicorp.com/terraform/language/expressions/types#maps-objects) to favor using the equal sign as the separator, e.g., `<KEY> = <VALUE>` 

See [this issue](https://github.com/hashicorp/terraform/issues/24198) for more details.

All this to say: exactly how would you like me to change the sample TF file I provided in this issue?

Thanks!

**Comment by deanhuynh** [comment]
You're absolutely right, sorry misunderstood how `jsonencode` works in Terraform. This actually looks to be an gap with our Public API not allowing the setting of this specific field for the Javascript source. Your setup should work for any other source settings (which you can see the options for by calling [this endpoint](https://docs.segmentapis.com/tag/Catalog#operation/getSourceMetadata) and taking a look at the `options` field. I'll put in a ticket to fix this for Javascript sources and let you know when it is done.

**Comment by deanhuynh** [comment]
Hi, this issue should be fixed now. Please use `website_url` as the setting to set the URL for Javascript sources. Thanks for your patience and let me know if you run into any other issues!

**Comment by dossy** [comment]
Thanks, @deanhuynh!  I can confirm that it's working as expected now.
