### ISSUE TITLE
Terraform Reverse ETL connections update not working

### ISSUE THREAD

**Issue by muhammadatifjav** [segmentio/terraform-provider-segment#122]
**Description**

One of our customers is trying to update the schedule for the reverse ETL using Terraform, but there is no update after Terraform runs. It seems like the Terraform module has not been updated since we moved to checkpointing via mappings in Reverse ETL, as there is no reference to the subscriptionID in the terraform.

_Filing this on behalf of aiden@thecommerce.co (useamp team)_

**To Reproduce**

Example Terraform code that triggers the issue:

```terraform
resource "segment_reverse_etl_model" "snowflake_shopify_subscriptions" {
source_id = segment_source.snowflake.id
name = "Dev-Shopify-Subscriptions"
description = "This model contains refined Shopify Subscription data from the Snowflake warehouse."

schedule_strategy = "SPECIFIC_DAYS"
schedule_config = jsonencode({
"days" : [0, 1, 2, 3, 4, 5, 6],
"hours" : [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22],
"timezone" : "Asia/Singapore",
})

query_identifier_column = "cursor"

query = <<-EOF
SELECT
*
FROM ....hubspot_profile;
EOF
}
```

**Comment by deanhuynh** [comment]
This should be fixed now in v1.2.0. Please let me know if you still have any trouble.
