### ISSUE TITLE
Add ability to create subscriptions/mappings for destinations

### ISSUE THREAD

**Issue by dmazzaNW** [segmentio/terraform-provider-segment#57]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but a very nice to have. 

**Describe the solution you'd like**
We at nerdwallet are trying to move entirely to IAC for our segment set up and as far as I can tell the only thing we are missing the ability to do is create mappings for destinations.

We currently have alot of manual interaction with the UI and resource creation has been a bit of the wild west. We have been attempting to reign it in with our own internally made tool that leverages the Public API to create resources, but would like our source and destinations entirely to be managed by a singular terraform repo. We really do not want users to have to go in and edit resources in the UI that much if at all

Again it looks like almost everything we need is in the module currently, sources, destinations, filters, tracking plans, but we are missing subscriptions and mappings which we use very heavily in our webhook and amplitude destinations

**Describe alternatives you've considered**

We have an internally developed CLI tool that uses the public API to create and manage resources.  The issue is it is a bit esoteric unless you are one of the three people that use it daily or built it. We also do not want to give out workspace owner or API tokens so freely 

**Additional context**

**Comment by deanhuynh** [comment]
Thanks for the feedback! I'm working on destination subscriptions at the moment and will update when it's ready.

**Comment by deanhuynh** [comment]
Destination subscriptions are [now released](https://registry.terraform.io/providers/segmentio/segment/latest/docs/resources/destination_subscription). I was informed that mappings are configurable through subscriptions as well, so that should cover both of your requests. Let us know if you run into any issues.
