### ISSUE TITLE
Unable to create resources when Source contains schema settings

### ISSUE THREAD

**Issue by sco-at-scg** [segmentio/terraform-provider-segment#73]
# Issue

Provider version: `0.7.0`

When trying to create resources (source, tracking_plan, etc), if *the Source has a schema settings defined*, the provider was unable to successfully create the resources.

```
Error: Unable to update Source schema settings

{
  "errors": [
    {
      "type": "bad-request",
      "message": "Source is not connected to a tracking plan: fields '???', '???', '???' cannot be updated"
    }
  ]
}
```

```tf
resource "segment_source" "my_source_with_schema_settings" {
  slug    = "my_source_slug"
  name    = "My Source"
  enabled = true
  metadata = {
    id = "abc123"
  }
  settings = jsonencode({
    "token" : "xyz321",
  })
  labels = [
    {
      key   = "env"
      value = "dev"
    },
  ]
  schema_settings = {
    forwarding_blocked_events_to = segment_source.my_source.id
    track = {
      allow_unplanned_events           = true
      allow_unplanned_event_properties = true
      allow_event_on_violations        = false
      allow_properties_on_violations   = true
      common_event_on_violations       = "ALLOW"
    }
    identify = {
      allow_traits_on_violations = false
      allow_unplanned_traits     = false
      common_event_on_violations = "ALLOW"
    }
    group = {
      allow_traits_on_violations = true
      allow_unplanned_traits     = true
      common_event_on_violations = "ALLOW"
    }
  }
}
```

The current workaround is to split the resources into 2 steps:

1.  Create a source, tracking plan, tracking plan connection, etc
2.  Once created, update the source with the \`schema\_settings\`

Ideal:

1.  Can we define the source with schema settings and other resources in one step process?

**Comment by cv** [comment]
Thank you for reporting this issue, @sco-at-scg! Looks like an issue with how we order the operations when creating sources. We'll post a PR with a potential fix here shortly.

**Comment by deanhuynh** [comment]
This is fixed in the newest release. Unfortunately a breaking change was required where the `schema_settings` had to be moved to the `segment_source_tracking_plan_connection` resource in order for the resources to be created in the correct order naturally.
