### ISSUE TITLE
No import documentation

### ISSUE THREAD

**Issue by johnkoehn** [segmentio/terraform-provider-segment#91]
**Is your feature request related to a problem? Please describe.**

Part of a good terraform provider is importing existing resources. However, no import documentation exits for the resources.

**Describe the solution you'd like**

I'd like import documentation

**Describe alternatives you've considered**

N/A

**Additional context**

Very happy to see this provider as we have multiple production environments across the globe with their own segment workspaces

**Comment by cv** [comment]
Hi @johnkoehn! 

We'll be working on imports (and associated documentation) shortly, and this helps us prioritize. Thank you for the suggestion!

**Comment by deanhuynh** [comment]
In the meantime, all resources are importable by their `id` unless otherwise noted in the docs as in [here](https://registry.terraform.io/providers/segmentio/segment/latest/docs/resources/destination_filter).

**Comment by deanhuynh** [comment]
The docs have been updated. Thank you for your patience.
