### ISSUE TITLE
Status of the project ?

### ISSUE THREAD

**Issue by thomas-oaknorth** [segmentio/terraform-provider-segment#93]
Hey,
What's the current status of the project ? Is it still being worked on and maintained ?
Quite keen to use this but basically don't want to commit to it if this is about to be abandoned.
Thanks !

**Comment by cv** [comment]
Hi @thomas-oaknorth!

This Terraform provider is under active development. Feel free to give it a try and let us know if you bump into any issues, and we'll work on them as quickly as possible.
